# Site settings
name: Sai Gutta
title: Sai Gutta | Computer System Engineer
description: a problem-solver and analyst in Information Technology area focused on automating operation process. 
url: https://sairao77.github.io/
baseurl: ''
email: sairao77@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: img/emojis/technologist.png
resume: /resume.pdf
crediturl: https://bchiang7.github.io
social:
  - title: email
    url: mailto:sairao77@gmail.com
  - title: github
    url: https://github.com/sairao77
  - title: linkedin
    url: https://www.linkedin.com/in/saigutta

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
